spring.application.name=hoodle
spring.mvc.servlet.path=/hoodle
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/hoodle
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
jwt.secret=mysupersecretjwttokenauthkey1209460989
app.jwt.token.message=Login Successful
jwt.issuer=hoodle-auth-service
jwt.expiration.ms=3600000